---

- name: RHEL | Install GitLab GPG key
  rpm_key:
    state: present
    key: https://packages.gitlab.com/runner/gitlab-runner/gpgkey
  when: ansible_os_family == 'RedHat'
  tags:
    - gitlab
    - gitlab-gpg

- name: Install GitLab Runner dependencies
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - pygpgme
    - yum-utils

- name: Add GitLab Runner rpm repo
  template:
    src: runner_gitlab-runner.repo.j2
    dest: /etc/yum.repos.d/runner_gitlab-runner.repo

- name: Install GitLab Runner
  yum:
    name: gitlab-runner
    state: latest
    update_cache: yes
