---
- name: Add GitLab apt key
  apt_key:
    url: https://packages.gitlab.com/gpg.key
    state: present

- name: Install GitLab Runner dependencies (Debian specific)
  apt:
    name: debian-archive-keyring
    state: present
  when: ansible_distribution == 'Debian'

- name: Install GitLab Runner dependencies
  apt:
    name: apt-transport-https
    state: present

- name: Add GitLab Runner apt repo
  apt_repository:
    repo: 'deb https://packages.gitlab.com/runner/gitlab-ci-multi-runner/{{ ansible_lsb.id|lower }}/ {{ ansible_lsb.codename|lower }} main'
    state: present

- name: Install GitLab Runner
  apt:
    name: gitlab-ci-multi-runner
    state: latest
    update_cache: yes
