---
- name: "Install GitLab Runner ({{ ansible_os_family }})"
  include: "{{ ansible_os_family | lower }}.yml"

- name: Set global options
  include: global-setup.yml

- name: Register GitLab Runner
  include: register-runner.yml
  when: gitlab_runner_registration_token != ''
