---
- name: List configured runners
  command: gitlab-runner list
  register: configured_runners
  changed_when: False

- name: Register runner to GitLab
  command: gitlab-runner register >
    --non-interactive
    --url '{{ gitlab_runner_coordinator_url }}'
    --registration-token '{{ gitlab_runner_registration_token }}'
    --description '{{ gitlab_runner_description }}'
    --tag-list '{{ gitlab_runner_tags | join(",") }}'
    --executor '{{ gitlab_runner_executor }}'
    --docker-image '{{ gitlab_runner_docker_image }}'
    {% if gitlab_runner_docker_privileged %} --docker-privileged {% endif %}
    {% for vol in gitlab_runner_docker_volumes %} --docker-volumes {{vol}} {% endfor %}
  when: configured_runners.stderr.find('\n{{ gitlab_runner_description }}') == -1
