---
- name: List configured runners
  command: gitlab-runner list
  register: configured_runners
  changed_when: False

- name: Register runner to GitLab
  command: gitlab-runner register >
    --non-interactive
    --url '{{ gitlab_runner_coordinator_url }}'
    --registration-token '{{ gitlab_runner_registration_token }}'
    --description '{{ gitlab_runner_description }}'
    --tag-list '{{ gitlab_runner_tags | join(",") }}'
    --executor '{{ gitlab_runner_executor }}'
    --docker-image '{{ gitlab_runner_docker_image }}'
    --ssh-user '{{gitlab_runner_ssh_user}}'
    --ssh-host '{{gitlab_runner_ssh_host}}'
    --ssh-port '{{gitlab_runner_ssh_port}}'
    --ssh-password '{{gitlab_runner_ssh_password}}'
    --ssh-identity-file '{{gitlab_runner_ssh_identity_file}}'
  when: configured_runners.stderr.find('\n{{ gitlab_runner_description }}') == -1
